import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import yaml from "js-yaml";
import { loadConfig } from "../config.js";
import {
  agentHermesProfile,
  agentHonchoWorkspace,
  agentPrompt,
  loadEcosystemConfig
} from "../ecosystem/ecosystemConfig.js";
import { skillManifestForIds } from "../skills/skillCatalog.js";

type Args = {
  outDir: string;
  homeDir?: string;
};

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const config = loadConfig();
  const ecosystem = await loadEcosystemConfig(config.ecosystemConfigPath);
  const outDir = path.resolve(process.cwd(), args.outDir);
  const homeDir = path.resolve(process.cwd(), args.homeDir ?? path.dirname(outDir));
  const allowedWhatsAppUsers = ecosystemWhatsAppAllowedUsers(ecosystem);

  await mkdir(outDir, { recursive: true });
  await writeHermesAtlasEnv(homeDir, allowedWhatsAppUsers);

  const manifest = {
    project: ecosystem.project,
    honchoBaseUrl: config.honcho?.baseUrl ?? "http://honcho-api:8000",
    messaging: {
      whatsappAllowedUsers: allowedWhatsAppUsers
    },
    profiles: ecosystem.agents.map((agent) => ({
      id: agent.id,
      displayName: agent.displayName,
      hermesProfile: agentHermesProfile(agent),
      honchoWorkspace: agentHonchoWorkspace(agent),
      skills: agent.skills
    }))
  };
  const desiredProfiles = new Set(manifest.profiles.map((profile) => profile.hermesProfile));

  await removeStaleProfiles(outDir, desiredProfiles);

  for (const agent of ecosystem.agents) {
    const profile = agentHermesProfile(agent);
    const profileDir = path.join(outDir, profile);
    const honchoWorkspace = agentHonchoWorkspace(agent);
    const skillManifest = skillManifestForIds(agent.skills);
    const honchoHosts = hermesHonchoHosts(profile, {
      aiPeer: agent.id,
      peerName: ecosystem.project.id,
      workspace: honchoWorkspace
    });

    await rm(profileDir, { recursive: true, force: true });
    await mkdir(profileDir, { recursive: true });
    await writeFile(
      path.join(profileDir, "config.yaml"),
      yaml.dump(
        {
          whatsapp: {
            unauthorized_dm_behavior: "ignore"
          },
          memory: {
            provider: "honcho",
            memory_enabled: true,
            user_profile_enabled: true
          }
        },
        { noRefs: true, lineWidth: 120 }
      ),
      "utf8"
    );
    await writeFile(path.join(profileDir, "SOUL.md"), `${agentPrompt(agent)}\n`, "utf8");
    await writeFile(
      path.join(profileDir, "skills.json"),
      `${JSON.stringify(
        {
          agentId: agent.id,
          skills: skillManifest,
          enforcement: {
            identity: "Hermes gateway allowlists generated from Atlas ecosystem config",
            approvals: "Atlas API",
            memory: "Hermes Honcho memory provider with Atlas-generated profile-local honcho.json",
            bridgeWrites: "iOS bridge scoped device tokens"
          }
        },
        null,
        2
      )}\n`,
      "utf8"
    );
    await writeFile(
      path.join(profileDir, "honcho.json"),
      `${JSON.stringify(
        {
          baseUrl: config.honcho?.baseUrl ?? "http://honcho-api:8000",
          apiKey: config.honcho?.apiKey || undefined,
          hosts: honchoHosts
        },
        null,
        2
      )}\n`,
      "utf8"
    );
  }

  await writeFile(path.join(outDir, "atlas-profiles.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  console.log(`Generated ${ecosystem.agents.length} Hermes profile(s) in ${outDir}`);
}

function ecosystemWhatsAppAllowedUsers(ecosystem: Awaited<ReturnType<typeof loadEcosystemConfig>>): string[] {
  const allowedUsers = new Set<string>();

  for (const user of ecosystem.users) {
    for (const identity of user.identities) {
      if (identity.channel !== "whatsapp" || !identity.enabled) {
        continue;
      }

      const normalized = normalizeWhatsAppUser(identity.externalId);
      if (normalized) {
        allowedUsers.add(normalized);
      }
    }
  }

  return [...allowedUsers].sort();
}

function normalizeWhatsAppUser(externalId: string): string {
  return externalId.replace(/\D/g, "");
}

async function writeHermesAtlasEnv(homeDir: string, allowedWhatsAppUsers: string[]): Promise<void> {
  await mkdir(homeDir, { recursive: true });

  const lines = [
    "# Generated by Atlas from ecosystem/atlas.yaml.",
    "# Keep provider credentials in Hermes' own .env or the root Atlas .env, not in this managed file.",
    ""
  ];

  if (allowedWhatsAppUsers.length > 0) {
    const allowlist = allowedWhatsAppUsers.join(",");
    lines.push("# Hermes WhatsApp gateway allowlists. Phone numbers use country code digits without '+'.");
    lines.push(`WHATSAPP_ALLOWED_USERS=${allowlist}`);
    lines.push(`WHATSAPP_CLOUD_ALLOWED_USERS=${allowlist}`);
  } else {
    lines.push("# No WhatsApp identities are configured; Hermes will deny inbound WhatsApp by default.");
  }

  await writeFile(path.join(homeDir, "atlas.env"), `${lines.join("\n")}\n`, "utf8");
}

type HonchoHostConfig = {
  enabled: true;
  aiPeer: string;
  peerName: string;
  workspace: string;
};

function hermesHonchoHosts(profile: string, host: Omit<HonchoHostConfig, "enabled">): Record<string, HonchoHostConfig> {
  const config = { enabled: true, ...host } satisfies HonchoHostConfig;
  const profileHostKey = profile === "default" || profile === "hermes" ? "hermes" : `hermes.${profile}`;

  return profileHostKey === "hermes" ? { hermes: config } : { hermes: config, [profileHostKey]: config };
}

async function removeStaleProfiles(outDir: string, desiredProfiles: Set<string>): Promise<void> {
  const manifestPath = path.join(outDir, "atlas-profiles.json");
  const previousProfiles = await readPreviousProfiles(manifestPath);

  for (const profile of previousProfiles) {
    if (!desiredProfiles.has(profile)) {
      await rm(path.join(outDir, profile), { recursive: true, force: true });
    }
  }
}

async function readPreviousProfiles(manifestPath: string): Promise<string[]> {
  try {
    const raw = await readFile(manifestPath, "utf8");
    const parsed = JSON.parse(raw) as {
      profiles?: Array<{ hermesProfile?: unknown }>;
    };

    return (
      parsed.profiles
        ?.map((profile) => profile.hermesProfile)
        .filter((profile): profile is string => typeof profile === "string" && profile.length > 0) ?? []
    );
  } catch {
    return [];
  }
}

function parseArgs(argv: string[]): Args {
  const outIndex = argv.indexOf("--out");
  const outDir = outIndex === -1 ? undefined : argv[outIndex + 1];
  const homeIndex = argv.indexOf("--home");
  const homeDir = homeIndex === -1 ? undefined : argv[homeIndex + 1];

  return { outDir: outDir ?? "data/hermes/profiles", homeDir };
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
